# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62ee3082ac9cc3b454333705374b1eb815d92ba82b1a59fb25b4adc1400be056cdb786f3a30505d870b8a999f77899e2a39d357605f4049402d8bc491f6a1bd2

test:
  secret_key_base: 76436da0198c92f115ac1e45e0e90aa889575b19575c60e5738970ebfc56abeaf4b6fe54e7bc5d1d6cd0fb8a8b000301f71b2ac4b8e115191a10d768ad61d4f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
